name: Deploy to DO Server

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Project"
        uses: actions/setup-node@master
        run: npm install && npm run build

      - name: "SCP Files"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "./dist/*"
          target: "/var/www/hcn"
